Get things to the externals stage.

diff --git a/scripts/autoinstall b/scripts/autoinstall
--- a/scripts/autoinstall
+++ b/scripts/autoinstall
@@ -8,12 +8,12 @@ options:
   -c <url>		: set URL for the config file
   -g <url>		: set URL for GARPI
   -f			: optimized-away things are force to happen
+
 EOF
     exit 0
 }
 
-cfgurl_svn="https://lbne.bnl.gov/svn/installation/trunk/AutoInstall/config/interim-latest.cfg"
-cfgurl=$cfgurl_svn
+cfgurl=""
 garpiurl_http="http://www.phy.bnl.gov/~bviren/garpi/releases/garpi-latest.tar.gz"
 garpiurl_git="ssh://gitosis@gateway.phy.bnl.gov/garpi"
 garpiurl="$garpiurl_http"
@@ -45,10 +45,12 @@ err () {
     exit 1
 }
 logcmd () {
+    log "Running: \"$*\""
     $* >> $logfile 2>&1
     ret=$?
     if [ "$ret" != "0" ] ; then
-	err="command \"$*\" failed with \"$err\""
+	err "command \"$*\" failed with code \"$ret\""
+	exit $ret
     fi
 }
 
@@ -147,43 +149,75 @@ get_unpack_garpi () {
 get_config () {
     url=$1 ; shift
     if [ -z "$url" ] ; then url=$cfgurl; fi
-    download_file $url
+    if [ -z "$url" ] ; then 
+	err 'get_config: no URL for configuration file'; 
+	exit 1
+    fi
+
+    if echo $url | grep -q ':' ; then 
+	download_file $url
+    else
+	echo $url
+    fi
 }
 
 initialize () {
     cfg=$(get_config)
+    if [ -z "$cfg" ] ; then exit 1; fi
     #info "got config: $cfg"
     cfg=$(make_absolute $cfg)
     #info "$cfg"
     garpidir=$(get_unpack_garpi)
     garpidir=$(make_absolute $garpidir)
-    info "Got garpidir \"$garpidir\""
+    #info "Got garpidir \"$garpidir\""
     cat <<EOF>ai-setup.sh
 garpi () {
   export GARPIROOT=$garpidir
+  export GARPICONFIG=$cfg
   export PYTHONPATH=\$GARPIROOT/python\${PYTHONPATH:+:\$PYTHONPATH}
-  \$GARPIROOT/scripts/garpi -c $cfg
+  \$GARPIROOT/scripts/garpi -c $cfg \$*
 }
 EOF
 }
 
-garpi_prereq () {
+prereq () {
     source ai-setup.sh
     logcmd garpi setup
     logcmd garpi install_cmt
-    if [ -n "$(grep ^url $cfgfile|grep '\Wgit\W')" -a -z "$(which git)" ] ; then
+    if [ -z "$cfgurl" ] ; then
+	cfgurl=$GARPICONFIG
+    fi
+    if [ -z "$cfgurl" ] ; then
+	err "No GARPI config file in neither the environment nor from the command line options"
+	exit 1
+    fi    
+    if [ -n "$(grep ^url $cfgurl|grep '\Wgit\W')" -a -z "$(which git)" ] ; then
 	logcmd garpi install_git
     fi
 }
-garpi_get_projects () {
+get_projects () {
+    source ai-setup.sh
+    info "Getting projects"
     logcmd garpi get_projects
+    info "Initializing projects"
     logcmd garpi init_projects
+}
+cmtconfig () {
+    source ai-setup.sh
     export CMTCONFIG=$(garpi print_cmtconfig)
     logcmd garpi test_cmtconfig $CMTCONFIG
-    cat <<EOF> garpi-setup.sh
+    info "Found CMTCONFIG=$CMTCONFIG"
+    cat <<EOF> cmtconfig-setup.sh
 export CMTCONFIG=$CMTCONFIG
 EOF
-    
+}    
+
+externals () {
+    source ai-setup.sh
+    source cmtconfig-setup.sh
+    info "Installing externals"
+    logcmd garpi externals
+}
 
 everything () {
     initialize
